[NPS-608] Remove AGB & data protection policy acceptance checkboxes f…
notebooksbilliger/ShopWare6-MainTheme pull request #15
Opened 2020-04-30 15:39 UTC by jacekwilczynski

2020-05-04 11:16 UTC, bartosz-zasada requested changes

2020-05-04 11:16 UTC, bartosz-zasada commented on composer.json
> +    "version": "1.0.13",
You should also write a short description of your changes in CHANGELOG.md.

2020-05-04 11:30 UTC, bartosz-zasada approved these changes

2020-05-04 13:00 UTC, patpilus commented
@jacekwilczynski could you please provide the screenshot with current view (after checkbox removal)?

2020-05-04 13:15 UTC, jacekwilczynski commented
> @jacekwilczynski could you please provide the screenshot with current view (after checkbox removal)?

ofc

![image](https://user-images.githubusercontent.com/26502857/80969534-0b69d300-8e1a-11ea-8cab-98cfd79a2b64.png)


![image](https://user-images.githubusercontent.com/26502857/80969517-00af3e00-8e1a-11ea-8d8d-c79655887817.png)

2020-05-05 07:02 UTC, patpilus approved these changes

2020-05-05 07:03 UTC, merged