[NPS-559] add GLightbox to display images, galleries, videos, iframes…
notebooksbilliger/ShopWare6-MainTheme pull request #8
Opened 2020-04-17 13:34 UTC by grovas

2020-04-17 14:07 UTC, bystro approved these changes

2020-04-20 07:13 UTC, patpilus commented on src/Resources/app/storefront/src/storefront/js/glightbox.js
> +(function (global, factory) {
Can't we install it with npm instead of putting 3rd party source code into our repository? 
`npm install glightbox`

2020-04-20 09:40 UTC, bartosz-zasada requested changes

2020-04-20 09:40 UTC, bartosz-zasada commented on package.json
> +  "license": "MIT",
proprietary

2020-04-20 10:02 UTC, grovas commented on package.json
> +  "license": "MIT",
of course :(

2020-04-20 10:09 UTC, patpilus approved these changes
38 new lines instead of 3000+ are looking much better ;) Please remember to use `Squash and merge` (not `Create a merge commit`) - thanks to that redundant merge commit wouldn't be present in master.

2020-04-20 10:09 UTC, patpilus commented on package.json
> +  "name": "maintheme",
I would add organization scope to the package name: `@nbb/maintheme`
https://docs.npmjs.com/misc/scope

2020-04-20 10:55 UTC, bartosz-zasada approved these changes

2020-04-20 11:13 UTC, merged